name: TownyPersistentToggle
version: ${project.version}
main: io.github.sulkywhale.townypersistenttoggle.TownyPersistentToggle
api-version: '1.21'
authors: [Sulky_Whale]
depend: [Towny]
folia-supported: true
